"use client";
import {useEffect,useState} from"react";
import{getCatalogOptions,getSfrs2020,runCalculation,type CatalogOptions,type Sfrs2020,type CalculationPayload}from"../lib/api";

const f0={hn:"9",n:"3",h:"3,6,9",w:"100,100,100",dn:"10",source:"project-2020-hazard-rev-A",site:"XD",sa02:"0.40",sa05:"0.35",sa10:"0.18",sa20:"0.09",sa50:"0.04",sa100:"0.02",pga:"0.20",pgv:"0.10",importance:"Low",period:"",higher:"",sfrs:"",interpolation:"LINEAR"};
const num=(s:string)=>{const n=Number(s);if(!Number.isFinite(n))throw new Error(`Invalid value: ${s}`);return n};
const list=(s:string)=>s.split(",").map(x=>Number(x.trim())).filter(Number.isFinite);
function Field({l,v,c}:{l:string;v:string;c:(x:string)=>void}){return <label className="field"><span>{l}</span><input value={v} onChange={e=>c(e.target.value)}/></label>}
function Sel({l,v,o,c}:{l:string;v:string;o:[string,string][];c:(x:string)=>void}){return <label className="field"><span>{l}</span><select value={v} onChange={e=>c(e.target.value)}>{o.map(([a,b])=><option key={a} value={a}>{b}</option>)}</select></label>}
function Table({t,v}:{t:string;v:unknown}){if(!v||typeof v!=="object"||Array.isArray(v))return null;return <div className="tableCard"><h3>{t}</h3><table><tbody>{Object.entries(v as Record<string,unknown>).filter(([,x])=>typeof x!=="object"||x===null).map(([k,x])=><tr key={k}><th>{k.replaceAll("_"," ")}</th><td>{x===null?"—":typeof x==="number"?x.toFixed(4):String(x)}</td></tr>)}</tbody></table></div>}
export default function EngineeringCalculator(){
 const [f,setF]=useState(f0),[o,setO]=useState<CatalogOptions|null>(null),[s,setS]=useState<Sfrs2020[]>([]),[r,setR]=useState<CalculationPayload|null>(null),[e,setE]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([getCatalogOptions(),getSfrs2020()]).then(([a,b])=>{setO(a);setS(b);setF(x=>({...x,period:a.period_system_types[0]??"",higher:a.higher_mode_system_types_2020[0]??"",sfrs:b[0]?.id??""}))}).catch(x=>setE(String(x)))},[]);
 async function run(){setBusy(true);setE("");try{const h=list(f.h),w=list(f.w),n=num(f.n);if(h.length!==n||w.length!==n)throw new Error("Storey lists must match number of storeys.");setR(await runCalculation({run_mode:"SINGLE_EDITION",code_edition:"NBCC_2020",common_inputs:{hn_m:num(f.hn),n_storeys:n,storey_heights_m:h,storey_weights_kn:w,global_dn_m:num(f.dn)},nbcc_2020:{hazard:{hazard_source_id:f.source,site_designation_x:f.site,sa_0_2_x:num(f.sa02),sa_0_5_x:num(f.sa05),sa_1_0_x:num(f.sa10),sa_2_0_x:num(f.sa20),sa_5_0_x:num(f.sa50),sa_10_0_x:num(f.sa100),pga_x:num(f.pga),pgv_x_m_s:num(f.pgv)},spectrum_interpolation_method:f.interpolation,importance_category:f.importance,period_system_type:f.period,sfrs_id_2020:f.sfrs,higher_mode_system_type:f.higher,irregularity_flags:Object.fromEntries(Array.from({length:10},(_,i)=>[i+1,false])),nonorthogonal_sfrs:false,continuous_wood_over_4_storeys:false}}))}catch(x){setE(x instanceof Error?x.message:"Calculation failed.")}finally{setBusy(false)}}
 const set=(k:keyof typeof f)=>(v:string)=>setF({...f,[k]:v});
 const out=(r?.results_by_edition.NBCC_2020?.outputs??{}) as Record<string,unknown>;
 return <main className="shell"><header className="hero"><div><p className="eyebrow">LinkoTech Engineering</p><h1>CNBC Seismic Calculator</h1><p>Structured NBCC 2020 engineering workspace</p></div><div className="heroMeta"><span>Specification v3.0</span><span>Engine v0.1.0</span></div></header><div className="releaseBanner"><strong>NBCC 2020 production approval is blocked.</strong><span>Use approved external hazard inputs. Engine warnings and limitations remain visible.</span></div>
 <section className="formSection"><div className="sectionTitle"><h2>Building model</h2><p>Common geometry and seismic weights.</p></div><div className="fieldGrid"><Field l="Building height Hn (m)" v={f.hn} c={set("hn")}/><Field l="Number of storeys" v={f.n} c={set("n")}/><Field l="Plan dimension Dn (m)" v={f.dn} c={set("dn")}/><Field l="Storey elevations (m)" v={f.h} c={set("h")}/><Field l="Storey weights (kN)" v={f.w} c={set("w")}/></div></section>
 <section className="formSection"><div className="sectionTitle"><h2>NBCC 2020 hazard and system</h2><p>{o?.nbcc_2020_hazard_note}</p></div><div className="fieldGrid"><Field l="Hazard source ID" v={f.source} c={set("source")}/><Field l="Site designation X" v={f.site} c={set("site")}/><Field l="Sa(0.2,X)" v={f.sa02} c={set("sa02")}/><Field l="Sa(0.5,X)" v={f.sa05} c={set("sa05")}/><Field l="Sa(1.0,X)" v={f.sa10} c={set("sa10")}/><Field l="Sa(2.0,X)" v={f.sa20} c={set("sa20")}/><Field l="Sa(5.0,X)" v={f.sa50} c={set("sa50")}/><Field l="Sa(10.0,X)" v={f.sa100} c={set("sa100")}/><Field l="PGA(X)" v={f.pga} c={set("pga")}/><Field l="PGV(X) m/s" v={f.pgv} c={set("pgv")}/>{o&&<><Sel l="Interpolation" v={f.interpolation} c={set("interpolation")} o={o.spectrum_interpolation_methods.map(x=>[x,x])}/><Sel l="Importance category" v={f.importance} c={set("importance")} o={o.importance_categories_2020.map(x=>[x,x])}/><Sel l="Period system" v={f.period} c={set("period")} o={o.period_system_types.map(x=>[x,x])}/><Sel l="Higher-mode system" v={f.higher} c={set("higher")} o={o.higher_mode_system_types_2020.map(x=>[x,x])}/><Sel l="SFRS" v={f.sfrs} c={set("sfrs")} o={s.map(x=>[x.id,`${x.name} · Rd ${x.Rd} · Ro ${x.Ro}`])}/></>}</div></section>
 {e&&<pre className="inlineError">{e}</pre>}<button className="runButton" onClick={run} disabled={busy||!o}>{busy?"Calculating…":"Run calculation"}</button>
 {r&&<section className="resultsArea"><div className="resultsTitle"><h2>Engineering results</h2><span>{r.checks.length} checks · {r.warnings.length} warnings</span></div><div className="resultGrid"><Table t="Hazard" v={out.hazard}/><Table t="Spectrum" v={out.spectrum}/><Table t="Classification" v={out.classification}/><Table t="SFRS" v={out.sfrs}/><Table t="Fundamental period" v={out.period}/><Table t="Higher mode" v={out.higher_mode}/><Table t="Base shear" v={out.static}/><Table t="Applicability" v={out.applicability}/></div><div className="reviewGrid"><div><h3>Checks</h3>{r.checks.map((x,i)=><article className="messageCard" key={i}><strong>{x.status} · {x.edition}</strong><p>{x.message}</p><small>{x.formula_id} {x.code_reference}</small></article>)}</div><div><h3>Warnings and limitations</h3>{r.warnings.map((x,i)=><article className="messageCard warning" key={i}><strong>{x.severity} · {x.edition}</strong><p>{x.message}</p><small>{x.formula_id} {x.code_reference}</small></article>)}</div></div></section>}
 </main>
}